### ISSUE TITLE
Create "self" autonomy telemetry & transmission (Trial 2)

### ISSUE THREAD

**Issue by rutheferd** [getditto/cod-polaris-m1#24]
**Definition of Done:** Data Structure in autonomy will be filled with telemetry data and then transmitted via appropriate protocol and the defined rate. Given a _broken_ connection the data will be saved locally.

**Comment by ajfabbri** [comment]
Adding "(Trial 2)" to title--thinking we'll need this but not for initial field trial, since that is focused on Contact Reports and Start/Stop.

**Comment by ajfabbri** [comment]
Closing older COD issues to make room for updated planning.
