### ISSUE TITLE
spike: how to implement v1 of start/stop mesage (Trial 1)

### ISSUE THREAD

**Issue by ajfabbri** [getditto/cod-polaris-m1#28]
Deliverable:
- Design / approach for implementing start/stop message functionality with ditto.

Approach: Easy-to-integrate v1 for initial trials. Iterate and improve architecture from there.

Our current thinking for v1 integration is to provide `av_server` COD middleware which handles the current REST API calls from autonomy, etc., and forwards them via Ditto to the base of operations. We could do something similar with start/stop, though the order is reversed; base is sending commands to the AV. We could have the AV poll (long poll) the REST endpoint and we return when we receive a message. We could also generate a TCP message and send it via AV localhost to the autonomy process.

**Comment by kitplummer** [comment]
For thought (perhaps beyond v1) - what are our options for a synchronous option?  For example if C2 "issues" a START message, how _could_ we handle ACKs?  And IF there were a "presence" message that the C2 node could consume to get a sense of who's in the MESH that would ACK...what might that look like?

**Comment by ajfabbri** [comment]
V2 begs the question: will the AV COD be a standalone process like v1 here, or will it be based on using the SDK in an existing process & container. Also relevant is how the existing inter-AV messaging works. We'd like to build something that doesn't require major rework in object recognition  or autonomy processes

**Comment by ajfabbri** [comment]
Any swarm / cluster algorithms should already have group management logic to track the set of nodes in the group. They should also have an RPC system used for tasking nodes with work requests, etc.. Seems like integrating with that flow is the eventual goal. The initiator / leader (who receives the start/end message) will already be disseminating that to the group and could provide response metadata to the base/C2 in response to Start message.
